version: '2.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUNDLER_VERSION: '2.0.1'
        NODE_MAJOR: '14'
        RUBY_VERSION: '2.7.3'
        YARN_VERSION: '1.13.0'
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
    environment:
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - EDITOR=vi
      - HISTFILE=/app/log/.bash_history
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - WEB_CONCURRENCY=1

  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '3000:3000'
      - '3002:3002'

  rails:
    <<: *backend
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && foreman start -f Procfile.dev"
    ports:
      - '3000:3000'

volumes:
  bundle:
  node_modules:
  rails_cache:
